### PR TITLE
GoogleServices-Info.plist path update

### PR DESCRIPTION
**Pull request by bhyoo99**
Corrected path to GoogleServices-Info.plist file
I think you made a typo. Is that right?

### CODE REVIEW

**Comment by itsramiel** [comment]
True that is incorrect; howver, it should be expo.ios.googleServicesFile not only expo.ios. If you can edit it, I'l merge it

> Corrected path to GoogleServices-Info.plist file I think you made a typo. Is that right?

**Comment by bhyoo99** [comment]
> True that is incorrect; howver, it should be expo.ios.googleServicesFile not only expo.ios. If you can edit it, I'l merge it
> 
> > Corrected path to GoogleServices-Info.plist file I think you made a typo. Is that right?

I did :) thanks!

**Review by itsramiel — APPROVED** [review]
Thank you for your contribution 🚀

**Comment by bhyoo99** [comment]
@itsramiel 
Thanks to this, I was able to apply FCM in iOS :) 
Have a nice day!

**Comment by itsramiel** [comment]
> @itsramiel Thanks to this, I was able to apply FCM in iOS :) Have a nice day!

Happy to be of help 🥳

**Pull request merged**
